---
title: "Exploratória (Lending Club)"
author: "Victor Duran"
date: "13 de agosto de 2016"
output: pdf_document
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = FALSE)

options(scipen = 999)
# install.packages("partykit")
library(partykit) #Para categorizar usando árvores

source("c:/Users/duranvr/Google Drive/R/functions/functionsMarkdown (1).R", encoding = "UTF-8")
source("c:/Users/duranvr/Documents/data_segmentation/functions/categorize_impact.R", encoding = "UTF-8")
```


```{r data cleaning, echo = FALSE, message = FALSE}

# dfAll <- read.table("c:/Users/Home/Google Drive/Mestrado/UFBA/Paulo/lending club data/loanAll.csv", header = TRUE, sep = ";", encoding = "UTF-8")

# #Transformando de factor em numeric int_rate e revol_util
# dfAll$int_rate <- as.numeric(gsub(pattern = "%", replacement = "", dfAll$int_rate))
# dfAll$revol_util <- as.numeric(gsub(pattern = "%", replacement = "", dfAll$revol_util))
# 
# #Removing emp_title, description and url
# dfAll$emp_title <- NULL
# dfAll$desc <- NULL
# dfAll$url <- NULL
# dfAll$title <- NULL
# 
# #Modificando o formato das datas
# lct <- Sys.getlocale("LC_TIME")
# Sys.setlocale("LC_TIME", "C")
# dfAll$issue_d <- as.Date(paste("1-", as.character(dfAll$issue_d), sep = ""), format = "%d-%b-%Y")
# dfAll$last_pymnt_d <- as.Date(paste("1-", as.character(dfAll$last_pymnt_d), sep = ""), format = "%d-%b-%Y")
# dfAll$next_pymnt_d <- as.Date(paste("1-", as.character(dfAll$next_pymnt_d), sep = ""), format = "%d-%b-%Y")
# dfAll$earliest_cr_line <- as.Date(paste("1-", as.character(dfAll$earliest_cr_line), sep = ""), format = "%d-%b-%Y")
# dfAll$last_credit_pull_d <- as.Date(paste("1-", as.character(dfAll$last_credit_pull_d), sep = ""), format = "%d-%b-%Y")
# Sys.setlocale("LC_TIME", lct)
# 
# #Transformando de fator em numérico total_il_high_credit_limit
# tmp <- dfAll$total_il_high_credit_limit
# tmp[tmp == ""] <- NA
# dfAll$total_il_high_credit_limit <- as.numeric(as.character(tmp))
# 
# #Reorganizando o banco em função da data do empréstimo
# dfAll <- dfAll[order(dfAll$issue_d),]
# 
# #Alterando os níveis de $term
# dfAll$term[dfAll$term == " 36 months"] <- "36 months"
# dfAll$term[dfAll$term == " 60 months"] <- "60 months"
# dfAll$term <- as.factor(as.character(dfAll$term))
# 
# 
# 
# #Definindo banco apenas com condições de interesse: Charged Off e Fully Paid
# dfGB <- dfAll[dfAll$loan_status == "Charged Off" | dfAll$loan_status == "Fully Paid",]
# 
# #Removendo os níveis anteriores do fator
# dfGB$loan_status <- as.factor(as.character(dfGB$loan_status))
# 
# colClasses <- sapply(dfGB, class)
# names(colClasses) <- NULL
# 
# paste(colClasses, collapse = "', '")
# 
# 
# write.table(dfGB, file = "c:/Users/Home/Google Drive/Mestrado/UFBA/Paulo/lending club data/dfGB.csv", sep = ";", row.names = FALSE, dec = ".", qmethod = "double")

#FIX ABOVE: Verif application status

dfGB <- read.table("c:/Users/duranvr/Google Drive/Mestrado/UFBA/Paulo/lending club data/dfGB.csv", header = TRUE, sep = ";", encoding = "UTF-8", colClasses = c('integer', 'integer', 'integer', 'integer', 'numeric', 'factor', 'numeric', 'numeric', 'factor', 'factor', 'factor', 'factor', 'numeric', 'factor', 'Date', 'factor', 'factor', 'factor', 'factor', 'factor', 'numeric', 'integer', 'Date', 'integer', 'integer', 'integer', 'integer', 'integer', 'integer', 'numeric', 'integer', 'factor', 'numeric', 'numeric', 'numeric', 'numeric', 'numeric', 'numeric', 'numeric', 'numeric', 'numeric', 'Date', 'numeric', 'Date', 'Date', 'integer', 'integer', 'integer', 'factor', 'numeric', 'numeric', 'factor', 'integer', 'integer', 'integer', 'integer', 'integer', 'integer', 'integer', 'integer', 'integer', 'numeric', 'integer', 'integer', 'integer', 'numeric', 'integer', 'integer', 'integer', 'integer', 'integer', 'integer', 'integer', 'numeric', 'integer', 'integer', 'integer', 'integer', 'integer', 'integer', 'integer', 'integer', 'integer', 'integer', 'integer', 'integer', 'integer', 'integer', 'integer', 'integer', 'integer', 'integer', 'integer', 'integer', 'integer', 'integer', 'integer', 'integer', 'integer', 'numeric', 'numeric', 'integer', 'integer', 'integer', 'integer', 'integer', 'numeric'))

# str(dfGB)
#### Removendo variáveis que não são obtidas no momento do pedido de empréstimo ####
posData <- c("recoveries", "collection_recovery_fee", "total_rec_late_fee",
             "total_pymnt", "total_rec_prncp", "total_pymnt_inv", "last_pymnt_d",
             "last_pymnt_amnt", "last_credit_pull_d", "mths_since_last_major_derog", 
             "inq_last_12m")

names(dfGB)
leaveNames <- c("id", "member_id", "loan_amnt", "funded_amnt", "funded_amnt_inv", "term", "int_rate", "installment", "grade", "sub_grade", "emp_length", "home_ownership", "annual_inc", "verification_status", "issue_d", "loan_status", "pymnt_plan", "purpose", "zip_code", "addr_state", "dti", "delinq_2yrs", "earliest_cr_line", "inq_last_6mths", "mths_since_last_delinq", "mths_since_last_record", "open_acc", "pub_rec", "revol_bal", "revol_util", "total_acc", "initial_list_status", "out_prncp", "out_prncp_inv", "total_pymnt", "total_pymnt_inv", "total_rec_prncp", "total_rec_int", "total_rec_late_fee", "recoveries", "collection_recovery_fee", "last_pymnt_d", "last_pymnt_amnt", "next_pymnt_d", "last_credit_pull_d", "collections_12_mths_ex_med", "mths_since_last_major_derog", "policy_code", "application_type", "annual_inc_joint", "dti_joint", "verification_status_joint", "acc_now_delinq", "tot_coll_amt", "tot_cur_bal", "open_acc_6m", "open_il_6m", "open_il_12m", "open_il_24m", "mths_since_rcnt_il", "total_bal_il", "il_util", "open_rv_12m", "open_rv_24m", "max_bal_bc", "all_util", "total_rev_hi_lim", "inq_fi", "total_cu_tl", "inq_last_12m")

names(dfGB)[!(names(dfGB) %in% leaveNames)]

# dfGB <- dfGB[,!(names(dfGB) %in% posData)]

#### Separação treino-validação-teste ####

plot(dfGB$issue_d)
hist(dfGB$issue_d, breaks = "months")
hist(dfGB$issue_d, breaks = "years")

indexTrain <- dfGB$issue_d < "2014-01-01"
indexValid <- (dfGB$issue_d < "2015-01-01" & dfGB$issue_d >= "2014-01-01")
indexTest <- (dfGB$issue_d < "2016-01-01" & dfGB$issue_d >= "2015-01-01")

dfGBTrain <- dfGB[indexTrain,]
dfGBValid <- dfGB[indexValid,]
dfGBTest <- dfGB[indexTest,]


```

```{r dt engineering}

numVars <- detectNum(dfGBTrain)

dfCat <- rep(NA, nrow(dfGBTrain))
for(i in 1:length(numVars)){
  tmp <- treeCat(dfGBTrain[,numVars[i]], dfGBTrain$loan_status, maxdepth = 2)
  dfCat <- data.frame(dfCat, tmp)
  names(dfCat)[i+1] <- names(numVars)[i]
}

nFactors <- sapply(dfCat, function(x){
  length(table(x))
})

#TODO: Precisa usar apenas os critérios do train set para definir os cortes e replicar as divisões para o valid e test set

table(nFactors)

```

```{r, echo = FALSE, message = FALSE}

#Definindo quais as variáveis do tipo factor
facVars <- sapply(dfGBTrain, function(x){
  class(x) == "factor"})
facVars <- which(facVars)

#Retirando zip code (muito granularizado)
facVars <- facVars[-c(10)]

numVars <- sapply(dfGBTrain, function(x){
  (class(x) == "integer") | (class(x) == "numeric")})
numVars <- which(numVars)

```


```{r}

impacts <- sapply(data.frame(dfCat[,nFactors > 1], dfGBTrain[,facVars]), 
                  crossImpact, vd = dfGBTrain$loan_status)

indexImp <- order(impacts[1,], decreasing = TRUE)

impactDf <- data.frame(varNames = colnames(impacts[,indexImp]), t(impacts[,indexImp]), stringsAsFactors = FALSE)

rmarkdownTable(impactDf)


```

```{r, echo = FALSE, message = FALSE}
#Factor Tables
facTablesTrain <- list(NA)
facTablesValid <- list(NA)
facTablesTest <- list(NA)

count <- 1
for(i in facVars){
  facTablesTrain[[count]] <- table.desc(dfGBTrain[,i])
  facTablesValid[[count]] <- table.desc(dfGBValid[,i]) 
  facTablesTest[[count]] <- table.desc(dfGBTest[,i])
  count <- count+1
}
names(facTablesTrain) <- names(facTablesValid) <- names(facTablesTest) <- names(facVars)

descTableTitle <- c("Loan term",
                    "Previously assigned credit grade",
                    "Previously assigned credit sub-grade",
                    "Employment length",
                    "Type of home ownership",
                    "Verification Status",
                    "Loan status (DV)",
                    "Payment plan",
                    "Purpose for taking the loan",
                    "Address State (US)",
                    "Initial list status",
                    "Application type",
                    "Verif application status")

#Numeric Table
numTableTrain <- numeric.desc(dfGBTrain[,numVars])
numTableValid <- numeric.desc(dfGBValid[,numVars])
numTableTest <- numeric.desc(dfGBValid[,numVars])

#Cross tables
facCrossTablesTrain <- list(NA)
facCrossTablesValid <- list(NA)
facCrossTablesTest <- list(NA)

count <- 1
for(i in facVars){
  facCrossTablesTrain[[count]] <- table.desc(dfGBTrain[,i], dfGBTrain$loan_status)
  facCrossTablesValid[[count]] <- table.desc(dfGBValid[,i], dfGBValid$loan_status)
  facCrossTablesTest[[count]] <- table.desc(dfGBTest[,i], dfGBTest$loan_status)
  count <- count+1
}
names(facCrossTablesTrain) <- names(facCrossTablesValid) <- names(facCrossTablesTest) <- names(facVars)

descCrossTableTitle <- c("Loan term",
                         "Previously assigned credit grade",
                         "Previously assigned credit sub-grade",
                         "Employment length",
                         "Type of home ownership",
                         "Verification Status",
                         "Loan status (DV)",
                         "Payment plan",
                         "Purpose for taking the loan",
                         "Address State (US)",
                         "Initial list status",
                         "Application type",
                         "Verif application status")

```

###Não numéricas:


```{r desc_categoric, echo = FALSE, results = 'asis'}

for(i in 1:length(facVars)){
  rmarkdownTable(facTablesTrain[[i]], paste("Train:", descTableTitle[i]))
  rmarkdownTable(facTablesValid[[i]], paste("Train:", descTableTitle[i]))
  rmarkdownTable(facTablesTest[[i]], paste("Train:", descTableTitle[i]))
}

```


###Numéricas:
```{r desc numeric, echo = FALSE, message=FALSE, results = 'asis'}

rmarkdownTable(numTableTrain, titulo = "Numeric descriptives train set")

rmarkdownTable(numTableValid, titulo = "Numeric descriptives validation set")

rmarkdownTable(numTableTest, titulo = "Numeric descriptives test set")

```


###Cruzando com Loan_status

```{r, echo = FALSE, message = FALSE, results = "asis"}

for(i in 1:length(facVars)){
  rmarkdownTable(facCrossTablesTrain[[i]], paste("Train: ", descCrossTableTitle[i]))
  rmarkdownTable(facCrossTablesValid[[i]], paste("Validation: ", descCrossTableTitle[i]))
  rmarkdownTable(facCrossTablesTest[[i]], paste("Test: ", descCrossTableTitle[i]))
}

```

```{r segmentation, echo = TRUE}
#Distributions for each segment
##Train
table(dfGBTrain$term, dfCat$loan_amnt[indexTrain])

##Valid
table(dfGBValid$term, dfCat$loan_amnt[indexValid])

##Test
table(dfGBTest$term, dfCat$loan_amnt[indexTest])

```

Note that in 2015 no 60 months customer took loans below 8k.

Should we use 7 categories only?

